services:
  vllm:
    command: --model erax-ai/EraX-VL-2B-V1.5 --tensor-parallel-size 1 --gpu-memory-utilization
      0.85 --max-model-len 8192 --block-size 32 --swap-space 8 --num-scheduler-steps
      2 --enable-chunked-prefill --max-num-batched-tokens 4096 --max-num-seqs 128
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    env_file:
    - /home/gitlab/.vllm/.env
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      timeout: 10s
    image: vllm/vllm-openai:latest
    ipc: host
    ports:
    - 8000:8000
    restart: unless-stopped
    runtime: nvidia
    volumes:
    - /home/gitlab/.cache/huggingface:/root/.cache/huggingface
    - /home/gitlab/.vllm/.env:/root/.env
version: '3.8'
